import greninja.writer;

void main()
{
  auto w = new Writer("build.ninja");

  // comment
  w.comment("Auto-generated by greninja");

  // compile rule
  w.rule("cc", "g++ -c $in -o $out");

  // link rule
  w.rule("link", "g++ $in -o $out");

  // object files
  w.build("main.o", "cc", "main.cpp");
  w.build("util.o", "cc", "util.cpp");

  // final binary
  w.build("app", "link", ["main.o", "util.o"]);

  // default target
  w._default(["app"]);

  w.close();

}
